name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Building
      uses: reuixiy/hugo-deploy@v1
      env:
        DEPLOY_REPO: zhangxu1814/zhangxu1814.github.io
        DEPLOY_BRANCH: build
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}